# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_name', models.CharField(max_length=200)),
                ('shirt_description', models.CharField(max_length=500)),
                ('size', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
