# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkartapp', '0002_auto_20160429_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
