# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkartapp', '0003_auto_20160502_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='size',
            field=models.CharField(max_length=1),
        ),
    ]
