# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkartapp', '0005_auto_20160502_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
